In [1]:
import numpy as np

In [3]:
# Task 1
HR=np.arange(1,4)
IT=np.arange(4,19)
Finance=np.arange(19,24)
Sales=np.arange(24,31)
print(f"No.of Employees in HR Department are{HR}")
print(f"No.of. Employees in IT department are{IT}")
print(f" No.of.Employees in Finance Department are{Finance}")
print(f"No.of.Employees in Sales department are{Sales}")

No.of Employees in HR Department are[1 2 3]
No.of. Employees in IT department are[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 No.of.Employees in Finance Department are[19 20 21 22 23]
No.of.Employees in Sales department are[24 25 26 27 28 29 30]


In [5]:
# Task 2
salary_for_HR=np.array([50,60,57])
print(salary_for_HR)
salary_for_IT=np.array([67]*15)
print(salary_for_IT)
salary_for_Finance=np.array([60,65,50,70,87])
print(salary_for_Finance)
salary_for_Sales=np.array([50,60,65,90,56,65,71])
print(salary_for_Sales)

[50 60 57]
[67 67 67 67 67 67 67 67 67 67 67 67 67 67 67]
[60 65 50 70 87]
[50 60 65 90 56 65 71]


In [7]:
# Task 3
avg_salary_for_HR=np.mean([salary_for_HR])
avg_salary_for_IT=np.mean([salary_for_IT])
avg_salary_for_Finance=np.mean([salary_for_Finance])
avg_salary_for_sales=np.mean([salary_for_Sales])
print(f"The average salary for HR is :{avg_salary_for_HR}")
print(f"The average salary for IT is :{avg_salary_for_IT}")
print(f"The average salary for Finance:{avg_salary_for_Finance}")
print(f"The average salary for Sales is :{avg_salary_for_sales}")
highest_average_salary = np.max([avg_salary_for_HR, avg_salary_for_IT, avg_salary_for_Finance, avg_salary_for_sales])
print("The highest_average_salary is:",highest_average_salary)
# Interpretation : from this i have found that highest average salary is 67.0 from the IT Department.

The average salary for HR is :55.666666666666664
The average salary for IT is :67.0
The average salary for Finance:66.4
The average salary for Sales is :65.28571428571429
The highest_average_salary is: 67.0


In [9]:
# Task 4
highest_salary_for_HR=np.max([salary_for_HR])
highest_salary_for_Finance=np.max([salary_for_Finance])
print("The highest salary for HR Is:",highest_salary_for_HR)
print("The highest salary for Finance Is:",highest_salary_for_Finance)

The highest salary for HR Is: 60
The highest salary for Finance Is: 87


In [15]:
# Task 5

In [11]:
salary_for_IT=salary_for_IT*1.05 
salary_for_IT

array([70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35,
       70.35, 70.35, 70.35, 70.35, 70.35, 70.35])